### PR TITLE
Update six minutes design

### PR DESCRIPTION
**Pull request by Bestem0r**
## Description

- Updates colors, icons and positions
- Replaces custom dialog component with shadcn dialog
- Adds restart button when game is over
- Adds animations to buttons and next song 
- Updates the 100 questions cards to match six minutes

Feedback is welcome! 😄

### Before

[Screencast from 2024-08-10 14-17-24.webm](https://github.com/user-attachments/assets/6dd482aa-153f-4dbd-92e3-3f8c7011905e)

### After

[Screencast from 2024-08-10 14-16-35.webm](https://github.com/user-attachments/assets/9565f881-dcfa-4e39-8f66-284bea0292c7)

### CODE REVIEW

**Comment by falbru** [comment]
Ok this is FUCKING EPIC!

Dette ble faktisk helt konge. Mye cleanere design. Digger det!! :100: :100: Ingenting å kommentere på

**Comment by falbru** [comment]
Ok det eneste jeg har å kommentere på er at kortet ikke alltid har plass til teksten:

image

**Review by falbru — APPROVED** [review]
forgot to approve lol. AMAZING!

**Comment by Bestem0r** [comment]
Thanks a lot @falbru! 😄😄 Made the play button and progress bar background white to increase the contrast a bit, and fixed the overflowing text. Merging it now!

**Pull request merged**
