### PR TITLE
Improve dice and lambo page

### PR DESCRIPTION
**Pull request by Bestem0r**
## Description

- Makes the back button on the lambo page visible again
- Fixes styling on the lambo page
- Adds back button to the dice page
- Adds beer container to the dice page

## Screenshots

| Before | After |
| -- | -- |
| Screenshot from 2024-08-07 12-36-53 | Screenshot from 2024-08-07 12-35-55 |
| Screenshot from 2024-08-07 12-36-35 | Screenshot from 2024-08-07 12-36-18 |

### CODE REVIEW

**Review by falbru — CHANGES_REQUESTED** [review]
Very nice :ok_hand: 

The only problem I found was that the Beer Container doesn't stretch to the bottom anymore on the startpage

Screenshot from 2024-08-07 16-46-30

**Comment by falbru** [comment]
image

hmm still not for some sizes

**Comment by Bestem0r** [comment]
> image
> 
> hmm still not for some sizes

What are the dimensions? I can'ta seem to reproduce it

**Review by falbru — APPROVED** [review]
Works great! Remember to rebase

**Pull request merged**
