### PR TITLE
Add home page

### PR DESCRIPTION
**Pull request by Bestem0r**
## Description

Adds a home page for navigating to the different songs and games. Any feedback is appreciated! 😄

### Desktop 

[Screencast from 2024-07-31 21-55-25.webm](https://github.com/user-attachments/assets/2afec33a-de89-40a2-bd6d-bdbb00399213)

### Mobile

[Screencast from 2024-07-31 21-56-18.webm](https://github.com/user-attachments/assets/48a8f2e3-0af2-4f03-bdc0-f640f0cdb4ee)

### CODE REVIEW

**Comment by falbru** [comment]
THIS👏LOOKS👏AWESOME👏🤩🤩🤩🤩🤩🤩🤩🤩🤩
Will review tomorrow!!!! Fantastic work!🥳

**Review by falbru — APPROVED** [review]
Excellent work! I love the beer wave and background!!!

I like that you chose a red background (because of Abakus). However, would a white background perhaps fit better? I think it would give it a more "modern" look

Very good job!

**Review by ivarnakken — APPROVED** [review]
I like!

Perhaps the wave moves a bit fast though? Wouldn't want anyone to get nauseous on vors 😆

**Comment by Bestem0r** [comment]
> Excellent work! I love the beer wave and background!!!
> 
> I like that you chose a red background (because of Abakus). However, would a white background perhaps fit better? I think it would give it a more "modern" look
> 
> Very good job!

Thank you! Good suggestion, I've made it white now. What do you think?

**Comment by falbru** [comment]
It looks awesome!

**Pull request merged**
